spring.application.name=notification-service



server.port=9094

# Webhook configuration
webhook.stripe.secret=dev-secret
webhook.paypal.secret=dev-secret
webhook.max-retries=3
webhook.retry-delay=300000


# =========================
# Kafka Consumer Config
# =========================
spring.kafka.consumer.group-id=notification-service-group
spring.kafka.consumer.auto-offset-reset=earliest
spring.kafka.consumer.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.consumer.value-deserializer=org.springframework.kafka.support.serializer.JsonDeserializer
spring.kafka.consumer.properties.spring.json.trusted.packages=com.banking.notification.dto.events

# =========================
# Notification Config
# =========================
notification.max-retries=3
notification.retry-interval-ms=300000

# =========================
# Email (SendGrid)
# =========================
notification.email.base-url=https://api.sendgrid.com
notification.email.api-key=${SENDGRID_API_KEY}

# =========================
# SMS (Twilio)
# =========================
notification.sms.base-url=https://api.twilio.com
notification.sms.account-sid=${TWILIO_ACCOUNT_SID}
notification.sms.auth-token=${TWILIO_AUTH_TOKEN}
notification.sms.from-number=${TWILIO_FROM_NUMBER}


# =========================
# Transaction Config
# =========================
transaction.reference-prefix=TXN
transaction.reconciliation.batch-size=100
transaction.reconciliation.schedule=0 0 2 * * ?
# =========================
# PostgreSQL R2DBC
# =========================
spring.r2dbc.url=r2dbc:postgresql://${DB_HOST:localhost}:5432/${DB_NAME:notification_db}
spring.r2dbc.username=${DB_USERNAME:admin}
spring.r2dbc.password=${DB_PASSWORD:admin}
spring.r2dbc.pool.initial-size=10
spring.r2dbc.pool.max-size=50
spring.r2dbc.pool.max-idle-time=30m

# =========================
# Liquibase (JDBC)
# =========================
spring.liquibase.enabled=true
spring.liquibase.change-log=classpath:db/changelog/db.changelog-master.xml
spring.liquibase.url=jdbc:postgresql://${DB_HOST:localhost}:5432/${DB_NAME:notification_db}
spring.liquibase.user=${DB_USERNAME:admin}
spring.liquibase.password=${DB_PASSWORD:admin}
spring.liquibase.drop-first=false
# =========================
# Redis
# =========================
spring.data.redis.host=${REDIS_HOST:localhost}
spring.data.redis.port=6379
spring.data.redis.timeout=6000ms

