spring.application.name=reconciliation-service

server.port=9095

# Webhook configuration
webhook.stripe.secret=dev-secret
webhook.paypal.secret=dev-secret
webhook.max-retries=3
webhook.retry-delay=300000


# =========================
# PostgreSQL R2DBC
# =========================
spring.r2dbc.url=r2dbc:postgresql://${DB_HOST:localhost}:5432/${DB_NAME:reconciliation_db}
spring.r2dbc.username=${DB_USERNAME:admin}
spring.r2dbc.password=${DB_PASSWORD:admin}
spring.r2dbc.pool.initial-size=10
spring.r2dbc.pool.max-size=50
spring.r2dbc.pool.max-idle-time=30m

# =========================
# Liquibase (JDBC)
# =========================
spring.liquibase.enabled=true
spring.liquibase.change-log=classpath:db/changelog/db.changelog-master.xml
spring.liquibase.url=jdbc:postgresql://${DB_HOST:localhost}:5432/${DB_NAME:reconciliation_db}
spring.liquibase.user=${DB_USERNAME:admin}
spring.liquibase.password=${DB_PASSWORD:admin}
spring.liquibase.drop-first=false
# =========================
# Redis
# =========================
spring.data.redis.host=${REDIS_HOST:localhost}
spring.data.redis.port=6379
spring.data.redis.timeout=6000ms



# =========================
# Kafka Producer Config
# =========================
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JsonSerializer

# =========================
# External Service URLs
# =========================
services.transaction.base-url=http://localhost:8083

services.stripe.base-url=https://api.stripe.com
services.stripe.api-key=${STRIPE_API_KEY}

