
# =========================
# Server
# =========================
server.port=9090

# =========================
# Spring Application
# =========================
spring.application.name=payment-service

# =========================
# PostgreSQL R2DBC
# =========================
spring.r2dbc.url=r2dbc:postgresql://${DB_HOST:localhost}:5432/${DB_NAME:payment_db}
spring.r2dbc.username=${DB_USERNAME:admin}
spring.r2dbc.password=${DB_PASSWORD:admin}
spring.r2dbc.pool.initial-size=10
spring.r2dbc.pool.max-size=50
spring.r2dbc.pool.max-idle-time=30m

# =========================
# Liquibase (JDBC)
# =========================
spring.liquibase.enabled=true
spring.liquibase.change-log=classpath:db/changelog/db.changelog-master.xml
spring.liquibase.url=jdbc:postgresql://${DB_HOST:localhost}:5432/${DB_NAME:payment_db}
spring.liquibase.user=${DB_USERNAME:admin}
spring.liquibase.password=${DB_PASSWORD:admin}
spring.liquibase.drop-first=false
# =========================
# Redis
# =========================
spring.data.redis.host=${REDIS_HOST:localhost}
spring.data.redis.port=6379
spring.data.redis.timeout=6000ms

# =========================
# RabbitMQ
# =========================
spring.rabbitmq.host=${RABBITMQ_HOST:localhost}
spring.rabbitmq.port=5672
spring.rabbitmq.username=${RABBITMQ_USERNAME:guest}
spring.rabbitmq.password=${RABBITQ_PASSWORD:guest}

spring.rabbitmq.listener.simple.retry.enabled=true
spring.rabbitmq.listener.simple.retry.max-attempts=3
spring.rabbitmq.listener.simple.retry.initial-interval=1000

# =========================
# Stripe Configuration
## =========================
#stripe.api.key=sk_test_51SvDjfCOLBMWcjSOZGPLmybm1FQ1wdSad9VbfCqEPMajioxhwEgqsImv3MPras6mTTvRe9r1O2DQ3Vu7PhKvSclr00UWAPafkq
stripe.api.key=webhook.stripe.secret=${STRIPE_WEBHOOK_SECRET}


stripe.webhook.secret=${STRIPE_WEBHOOK_SECRET:whsec_your_secret}

# =========================
# Actuator / Monitoring
# =========================
management.endpoints.web.exposure.include=health,info,metrics,prometheus
management.endpoint.health.probes.enabled=true
management.endpoint.health.show-details=always
management.health.livenessState.enabled=true
management.health.readinessState.enabled=true
management.metrics.export.prometheus.enabled=true

# =========================
# Logging
# =========================
logging.level.com.corebanking.payment=DEBUG
logging.level.org.springframework.r2dbc=DEBUG
logging.level.org.springframework.amqp=INFO
logging.pattern.console=%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n
